--  문자 함수
--  CHR(N) : ASCII 값을 문자로 변환

SELECT 1 FROM DUAL;     --  DUAL : 가상테이블 : 값만 알아볼때 많이 쓰인다.

SELECT CHR(65) FROM DUAL;

SELECT 'AAAA' || CHR(97) || 'BBBB'
FROM DUAL;

--  LPAD(RPAD) 나머지를 특정 문자로 채운다
SELECT LPAD('BBB',10, ) FROM DUAL;  --      BBB

SELECT LPAD('BBB',10, '-') FROM DUAL;   -- ------BB

SELECT RPAD('BBB',10) FROM DUAL;   -- BBB

SELECT RPAD('BBB',10, '-') FROM DUAL; -- BBB------

--INSTR : INDEXOF

-- 찾는 문자열
SELECT INSTR('A1234B5678A1234B', 'A')
FROM DUAL;

-- 찾는 문자열 , 찾는위치
SELECT INSTR('A1234B5678A1234B', 'A', 2)
FROM DUAL;

SELECT INSTR('A1234B5678A1234B', 'B', 7)
FROM DUAL;

-- 찾는 문자열 ,첫번째 위치, 첫번째위치 제외 찾는위치
SELECT INSTR('A1234B5678A1234B', 'B', 1, 1)
FROM DUAL;

SELECT INSTR('A1234B5678A1234B', 'A', 1, 1)
FROM DUAL;

-- REPLACE : 문자열 치환(문자열)
SELECT REPLACE('AAAAAAAAAAAAASCACDA','A')
FROM DUAL;

SELECT REPLACE('AAAAAAAAAAAAASCACDA','A', 'ㄱ')
FROM DUAL;

SELECT REPLACE('AAAAAAVVVVVVASCACDA','AA', 'ㄱ')
FROM DUAL;

-- TRANSLATE : 문자 치환(문자) 한문자씩밖에 바꿀수가 없다.
SELECT TRANSLATE('AAAAAAAAAAAAASCACDA','A','ㄱ')
FROM DUAL;

SELECT TRANSLATE('AAAAAAVVVVVVASCACDA','AA', 'ㄱ') -- X 한문자씩 바뀜
FROM DUAL;

--  숫자 함수
SELECT CEIL(13.5) -- 14 올림
FROM DUAL;

SELECT ROUND(13.5) -- 14 반올림 
FROM DUAL;

SELECT FLOOR(13.5) -- 13 나머지 버림
FROM DUAL;

SELECT MOD(5, 3) -- 2 나눈 나머지 값
FROM DUAL;

SELECT MOD(5, 7) -- 7 나눈 나머지 값
FROM DUAL;

SELECT POWER(2, 3) -- 8  2의 3승 값 
FROM DUAL;

-- 부호 +, 0, -
SELECT SIGN(13.4) -- 1 
FROM DUAL;

SELECT SIGN(0) -- 0
FROM DUAL;

SELECT SIGN(-1.4) -- -1
FROM DUAL;

-- 버림

SELECT TRUNC(13.123456) -- 13 소숫점 아래 버림
FROM DUAL;

SELECT TRUNC(13.123456, 3) -- 13 소숫점 3번째 이후로 버림
FROM DUAL;

SELECT TRUNC(13.123456, -1) -- 10 소숫점 -1번째 이후로 버림
FROM DUAL;


SELECT ASCII('A') -- CHR의 반대 ASCII코드 값을 숫자로 반환
FROM DUAL;


--  변환 함수 DATE --> STRING 변환할때 많이 쓰인다.

--TO_CHAR

SELECT TO_CHAR(SYSDATE) FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS') -- 날짜를 문자열로 변환
FROM DUAL;

SELECT TO_CHAR(100000000, '999,999,999') -- 숫자, 금액 포맷팅 예제
FROM DUAL;

SELECT TO_DATE('20180424') -- 날짜 포맷팅 예제
FROM DUAL;

SELECT TO_DATE('20180424', 'YYYYMMDD') -- 날짜 포맷팅 예제
FROM DUAL;

SELECT TO_DATE('04242018', 'MMDDYYYY') -- 날짜 포맷팅 예제
FROM DUAL;

--PARSEINT()
SELECT TO_NUMBER('100')+1
FROM DUAL;

--  날짜 함수
SELECT SYSDATE, ADD_MONTHS(SYSDATE, 1) -- 날짜의 N만큼 더한 일자
FROM DUAL;

-- 해당하는 월의 마지막 일자
SELECT LAST_DAY(SYSDATE) FROM DUAL;

-- 4월달 마지막 일자
SELECT LAST_DAY(TO_DATE('2018-04-24', 'YYYY-MM-DD')) FROM DUAL;

--SUBSTRING 
SELECT SUBSTR('ABCDEFG',3) FROM DUAL; -- 3번째 문자열부터
SELECT SUBSTR('ABCDEFG',3,1) FROM DUAL; -- 3번째 문자열부터 1개

--LENGTH
SELECT LENGTH('ABCDEFG') FROM DUAL; -- 문자열 길이


