/*
    ORDER BY == 정렬
    오름 / 내림
    
    SELECT
    WHERE
    WHERE
    GROUP BY
    ORDER BY -- 맨 밑에서 사용
    
*/

SELECT * FROM EMPLOYEES;

-- 급여 오름차순
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
ORDER BY SALARY;

-- JOBID 'IT_PROG' 인 사람의 급여 내림차순
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG'
ORDER BY SALARY DESC;

-- MANAGER_ID NULL 부터 오름차순
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID
FROM EMPLOYEES
ORDER BY MANAGER_ID NULLS FIRST;

-- MANAGER_ID NULL 부터 오름차순 그리고 급여 내림차순
SELECT FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID
FROM EMPLOYEES
ORDER BY MANAGER_ID NULLS FIRST, SALARY DESC;


SELECT FIRST_NAME, LAST_NAME, SALARY*12 AS 연봉
FROM EMPLOYEES
ORDER BY 연봉 DESC;

-- 2017-12-11
-- 문제 1 EMPLOYEES 테이블에서 입사일자 순으로 정렬하여 사원번호, 이름, 업무, 급여, 입사일자, 부서번호를 출력하라
SELECT * FROM EMPLOYEES;

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, SALARY, HIRE_DATE, DEPARTMENT_ID
FROM EMPLOYEES
ORDER BY HIRE_DATE;

-- 문제 2 EMPLOYEES 테이블에서 가장 최근에 입사한 순으로 사원번호, 이름, 업무, 급여, 입사일자,부서번호를 출력하라
SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, SALARY, HIRE_DATE, DEPARTMENT_ID
FROM EMPLOYEES
ORDER BY HIRE_DATE DESC;

-- 3
SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID, SALARY
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID, SALARY DESC, HIRE_DATE DESC;

-- 4 EMPLOYEES 테이블에서 첫번째 정렬은 부서번호로 
-- 두번째
SELECT LAST_NAME, HIRE_DATE, DEPARTMENT_ID, JOB_ID, SALARY
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID, JOB_ID, SALARY DESC;

-- SCOTT 계정
SELECT * FROM EMP;

--1
SELECT EMPNO, ENAME, HIREDATE
FROM EMP
ORDER BY HIREDATE DESC;

--2
SELECT ENAME, EMPNO
FROM EMP
ORDER BY SALARY DESC;

--3
SELECT ENAME, EMPNO, DEPTNO
FROM EMP
WHERE DEPTNO IN(10, 20)
ORDER BY ENAME ASC;

--4
SELECT ENAME, SAL, COMM
FROM EMP
WHERE COMM IS NOT NULL -- NULL 데이터 제거
ORDER BY COMM DESC;