/*
    SUB QUERY : QUERY 안의 QUERY
    
    단일 행 서브쿼리
    
    단일 행 다중쿼리
    
    SELECT  서브 쿼리 단일컬럼
    FROM 다중
    WHERE 다중
    
*/

SELECT FIRST_NAME, (SELECT MAX(MAX_SALARY) FROM JOBS) -- SELECT내 SUB QUERY는 컬럼은 1개만 가능
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

SELECT FIRST_NAME, LAST_NAME, SALARY, JOB_ID 
FROM EMPLOYEES
WHERE(SALARY, JOB_ID) = ( SELECT SALARY, JOB_ID 
                            FROM EMPLOYEES 
                            WHERE EMPLOYEE_ID = 101 );


SELECT EMPLOYEE_ID, FIRST_NAME
FROM EMPLOYEES
WHERE JOB_ID IN (SELECT JOB_ID FROM JOBS);
--WHERE JOB_ID = ANY(SELECT JOB_ID FROM JOBS);

SELECT EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID 
FROM JOB_HISTORY
WHERE (EMPLOYEE_ID, START_DATE) IN(SELECT EMPLOYEE_ID, HIRE_DATE FROM EMPLOYEES);

-- FROM SUB QUERY
SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.JOB_ID, B.SAL_SUM 
FROM EMPLOYEES A, (SELECT JOB_ID, SUM(SALARY) AS SAL_SUM 
                        FROM EMPLOYEES
                        GROUP BY JOB_ID) B
WHERE A.JOB_ID = B.JOB_ID;

SELECT FIRST_NAME, A.SALARY, DEPT_SAL, (SELECT AVG(SALARY)    
                                            FROM EMPLOYEES C
                                            WHERE A.JOB_ID = C.JOB_ID)
FROM EMPLOYEES A, (SELECT DEPARTMENT_ID, AVG(SALARY) AS DEPT_SAL 
                        FROM EMPLOYEES
                        GROUP BY DEPARTMENT_ID) B
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID
AND A.SALARY > (SELECT AVG(SALARY) 
                    FROM EMPLOYEES D
                    WHERE A.JOB_ID = D.JOB_ID);
                    
                    
-- 특수 쿼리
-- CASE

SELECT EMPLOYEE_ID, FIRST_NAME, PHONE_NUMBER,
    CASE SUBSTR(PHONE_NUMBER, 1, 3)
        WHEN '515' THEN '서울'
        WHEN '590' THEN '대전'
        WHEN '659' THEN '부산'
        WHEN '603' THEN '광주'
        ELSE '기타' END  AS 지역
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, PHONE_NUMBER,
    CASE WHEN SUBSTR(PHONE_NUMBER, 1, 3) = '515' THEN '서울'
         WHEN SUBSTR(PHONE_NUMBER, 1, 3) = '590' THEN '대전'
         WHEN SUBSTR(PHONE_NUMBER, 1, 3) = '659' THEN '부산'
         WHEN SUBSTR(PHONE_NUMBER, 1, 3) = '515' THEN '광주'
         ELSE '기타' END AS 지역
FROM EMPLOYEES;

-- DECODE
SELECT EMPLOYEE_ID, FIRST_NAME, PHONE_NUMBER, 
    DECODE(SUBSTR(PHONE_NUMBER, 1, 3),
        '515','서울','590','대전','659','부산',
        '603','광주','기타') AS 지역
FROM EMPLOYEES;


-- NVL2
-- MANAGER ID 있으면 '직원' 없으면' 사장'
-- NVL2 (대상컬럼, NULL이 아니면, NULL 이면)
SELECT LAST_NAME, NVL2(MANAGER_ID, '직원','사장')
FROM EMPLOYEES;


--분석 함수
SELECT FIRST_NAME, JOB_ID, SALARY,
    RANK() OVER(ORDER BY SALARY DESC) AS RANK,              -- RANK 독립 같은 순위는 같은 숫자로 표시 후 같은수 COUNT 센다 출력 EX) 1224
    DENSE_RANK() OVER(ORDER BY SALARY DESC) AS DENSE_RANK,  -- 같은 순위는 같은숫자로 표시 같은수 COUNT 세지않는다. EX) 1223
    ROW_NUMBER() OVER(ORDER BY SALARY DESC) AS ROW_NUM
FROM EMPLOYEES
ORDER BY SALARY DESC;


SELECT FIRST_NAME, JOB_ID, SALARY
FROM EMPLOYEES
WHERE ROWNUM <=10 AND ROWNUM >=20     -- 상위 5명출력 시
ORDER BY SALARY DESC;

SELECT * FROM JOBS

SELECT FIRST_NAME, JOB_ID, CASE JOB_ID  WHEN 'AD_PRES' THEN 'A'
                                        WHEN 'ANALYST' THEN 'B'
                                        WHEN 'FI_MGR' THEN 'C'
                                        WHEN 'SA_MAN' THEN 'D'
                                        WHEN 'ST_CLERK' THEN 'E'
                                        ELSE '기타' END AS 직급
FROM EMPLOYEES


-- 문제1) EMPLOYEES 테이블에서 Kochhar의 급여보다 많은 사원의 정보를 사원번호,이름,담당업무,급여를 출력하라.

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, SALARY
FROM EMPLOYEES
WHERE (SALARY) > (SELECT SALARY FROM EMPLOYEES WHERE LAST_NAME ='Kochhar')
ORDER BY SALARY DESC;

-- 문제2) EMPLOYEES 테이블에서 급여의 평균보다 적은 사원의 정보를 사원번호,이름,담당업무,급여,부서번호를 출력하여라.

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE SALARY < (SELECT AVG(SALARY) FROM EMPLOYEES);

-- 문제3) EMPLOYEES 테이블에서 100번 부서의 최소 급여보다 최소 급여가 많은 다른 모든 부서를 출력하라

SELECT DEPARTMENT_ID, MIN(SALARY)
FROM EMPLOYEES 
GROUP BY DEPARTMENT_ID
HAVING MIN(SALARY) > (SELECT MIN(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = 100 );

-- 문제4) 업무별로 최소 급여를 받는 사원의 정보를 사원번호,이름,업무,부서번호를 출력하여라. 단 업무별로 정렬하여라.

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, MIN(SALARY)
FROM EMPLOYEES


HAVING JOB_ID, MIN(SALARY) = (SELECT JOB_ID, MIN(SALARY) FROM EMPLOYEES GROUP BY JOB_ID)



