
CREATE TABLE USERDTO(
	ID VARCHAR2(50),
	NAME VARCHAR2(50),
	AGE NUMBER(20),
	JOINDATE DATE
);

INSERT INTO USERDTO(ID, NAME, AGE, JOINDATE)
VALUES('ABC','홍길동',24,SYSDATE);

INSERT INTO USERDTO(ID, NAME, AGE, JOINDATE)
VALUES('BBB','철수',27,SYSDATE);

INSERT INTO USERDTO(ID, NAME, AGE, JOINDATE)
VALUES('CCC','영희',28,SYSDATE);

SELECT * FROM USERDTO;