-- 문제1) EMPLOYEES 테이블에서 부서별로 인원수,평균 급여,급여의 합,최소 급여,최대 급여를 포함하는 EMP_DEPTNO 테이블을 생성하라.
CREATE TABLE EMP_DEPTNO(DEPRTNO, E_COUNT, E_AVG, E_SUM, E_MIN, E_MAX) AS
(SELECT DEPARTMENT_ID, COUNT(DEPARTMENT_ID), AVG(SALARY), SUM(SALARY), MIN(SALARY), MAX(SALARY)  FROM EMPLOYEES GROUP BY DEPARTMENT_ID);

CREATE TABLE EMP_DEPTNO("부서번호","인원수","평균 급여","급여의 합","최소 급여","최대 급여")
AS
SELECT DEPARTMENT_ID, COUNT(*), AVG(SALARY), SUM(SALARY), MAX(SALARY), MIN(SALARY) FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

-- 문제2) EMP_DEPTNO 테이블에 ETC COLUMN을 추가하라. 단 자료형은 VARCHAR2(50) 사용하라.
ALTER TABLE EMP_DEPTNO 
ADD ETC VARCHAR2(50);


-- 문제3) EMP_DEPTNO 테이블에 ETC COLUMN을 수정하라. 자료 형은 VARCHAR2(15)로 하라.
ALTER TABLE EMP_DEPTNO
MODIFY ETC VARCHAR(15);

-- 문제4) EMP_DEPTNO 테이블에 있는 ETC 을 삭제하고 확인하라.
ALTER TABLE EMP_DEPTNO
DROP COLUMN ETC;

-- 문제5) 이전에 생성한 EMP_DEPTNO 테이블의 이름을 EMP_DEPT로 변경하라.
RENAME EMP_DEPTNO TO EMP_DEPT;

-- 문제6) EMP_DEPT 테이블을 삭제하라.
DROP TABLE EMP_DEPT;

-- 문제7) EMPLOYEES 테이블을 EMP 테이블을 생성하고 복제하도록 하라.(데이터 포함)
CREATE TABLE EMP AS (SELECT * FROM EMPLOYEES);


-- 문제8) EMP 테이블에 row를 추가해 봅니다. 다만, 반드시 데이터를 기입을 안해도 되면, NULL로 설정하도록 한다.
SELECT * FROM EMP;

INSERT INTO EMP (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) -- 생략가능
VALUES('853','A','B','EM','','08/10/10','SA_MAN','100','','','80');

INSERT INTO EMP
VALUES(1001,NULL,'KIM','ABC@NAVER.COM',NULL,SYSDATE,'IT_PROG',NULL,NULL,NULL,NULL);

-- 문제9) EMPLOYEES 테이블에서 EMPNO,ENAME,SAL,HIREDATE의 COLUMN만 선택하여 EMP_10 테이블을 생성(데이터 미포함)한 후 10번 부서만 선택하여 이에 대응하는 값을 EMP_10테이블에 입력하라.
CREATE TABLE EMP_10(EMPNO,ENAME,SAL,HIREDATE) AS (SELECT EMPLOYEE_ID, LAST_NAME, SALARY, HIRE_DATE FROM EMP WHERE 1=2);

SELECT * FROM EMP_10;

SELECT * FROM EMP;

INSERT INTO EMP_10
SELECT EMPLOYEE_ID, LAST_NAME, SALARY, HIRE_DATE
FROM EMP
WHERE DEPARTMENT_ID = 10;

/*
문제10) 다음은 무결성 제약 조건이 위배된 쿼리이다.
무엇을 위배했는지 알아보도록 합시다.

-- 설정 정보 확인
DESC EMPLOYEES;

1.사원번호가 NULL값이 아니어야하고, 중복되지않게 설정해야함, PRIMARY KEY

INSERT INTO EMPLOYEES
VALUES (100, NULL, 'YOON', 'dbs', NULL, SYSDATE, 'ST_MAN', NULL, NULL, NULL, NULL);	

INSERT INTO EMPLOYEES
VALUES (98, NULL, 'YOON', 'dbs', NULL, SYSDATE, 'ST_MAN', NULL, NULL, NULL, 100);

INSERT INTO EMPLOYEES
VALUES (98, NULL, 'YOON', 'dbs2', NULL, SYSDATE, 'ST_MAN', NULL, NULL, NULL, 101);
*/

-- 문제11) EMPLOYEES 테이블에서 사원 번호가 107인 사원의 부서를 10번으로 변경하여라.
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = 107; -- EMPLOYEE_ID 107 테이블 조회용

-- 결과
UPDATE EMPLOYEES
SET EMPLOYEE_ID = 10
WHERE EMPLOYEE_ID = 107;

-- 확인 후 되돌리기
ROLLBACK;

--  문제12) EMPLOYEES 테이블에서 사원 번호가 180인 사원의 부서를 20, 급여를 3500으로 변경하여라.
SELECT EMPLOYEE_ID, DEPARTMENT_ID, SALARY
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 180;

UPDATE EMPLOYEES
SET DEPARTMENT_ID = '20', SALARY = '3500'
WHERE EMPLOYEE_ID = 180;

-- 문제13) EMPLOYEES 테이블에서 Smith의 업무와 급여가 Hall의 업무와 급여와 일치하도록 수정하라.
UPDATE EMPLOYEES
SET (JOB_ID, SALARY) = (SELECT JOB_ID, SALARY FROM EMPLOYEES WHERE FIRST_NAME ='Lindsey' AND LAST_NAME='Smith')
WHERE LAST_NAME = 'Hall';


UPDATE EMPLOYEES
SET (JOB_ID, SALARY) = (SELECT JOB_ID, SALARY FROM EMPLOYEES WHERE LAST_NAME = 'Hall')
WHERE LAST_NAME = 'Smith';


-- ROW 삭제
DELETE EMPLOYEES
WHERE LAST_NAME ='B';